{"name": "test_login_fail", "status": "broken", "statusDetails": {"message": "KeyError: 'object'", "trace": "@pytest.fixture(scope='session',autouse=True)\n    def session_fixture():\n        path=\"/api/auth/login\"\n        data={'username':CommonData.mobile,\n              'password':CommonData.password}\n        resp=http.post(path,data)\n>       CommonData.token=resp['object']['token']\nE       KeyError: 'object'\n\nconftest.py:12: KeyError"}, "start": 1586572691551, "stop": 1586572691551, "uuid": "5b0ea4c5-01c6-4f42-82e6-b73b2d2d5bd5", "historyId": "d5aa2d4c30141e065bdea4986e12b366", "testCaseId": "7905a6c5755046c2c5777623dbba9faf", "fullName": "testcases.sys.test_sys_login.Test_login#test_login_fail", "labels": [{"name": "story", "value": "登录失败"}, {"name": "parentSuite", "value": "testcases.sys"}, {"name": "suite", "value": "test_sys_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-RML6UCN"}, {"name": "thread", "value": "38512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.sys.test_sys_login"}]}